Greg0\LibraryBundle\Entity\BookProperty:
    type: entity
    table: book_property
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToMany:
        bookVersion:
            targetEntity: BookVersion
            cascade: {  }
            fetch: LAZY
            mappedBy: bookProperty
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
