Greg0\LibraryBundle\Entity\BookVersion:
    type: entity
    table: book_version
    indexes:
        book_id:
            columns:
                - book_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    manyToOne:
        book:
            targetEntity: Book
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                book_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        bookProperty:
            targetEntity: BookProperty
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: bookVersion
            joinTable:
                name: book_versions_book_properties
                joinColumns:
                    -
                        name: book_version_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: book_property_id
                        referencedColumnName: id
            orderBy: null
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: bookVersion
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
