Greg0\LibraryBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Greg0\LibraryBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        outgoingBorrows:
            targetEntity: Borrow
            mappedBy: requestUser
        incomingBorrows:
            targetEntity: Borrow
            mappedBy: targetUser
    manyToMany:
        books:
            targetEntity: Book
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: users_books
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: book_id
                        referencedColumnName: id
            orderBy: null
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    lifecycleCallbacks: {}
