<?php

namespace Greg0\LibraryBundle\Repository;

use Greg0\LibraryBundle\Entity\User;

/**
 * BorrowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForRequestUser(User $user)
    {
        return $this->findBy(['requestUser' => $user], ['id' => 'DESC']);
    }

    public function findAllForTargetUser(User $user)
    {
        return $this->findBy(['targetUser' => $user], ['id' => 'DESC']);
    }
}
